export const Copy = {
  appName: 'SWIPE',
  tagline: 'Campus connections and academic planning',
  connect: 'Connect',
  skip: 'Skip',
  next: 'Next',
  save: 'Save',
  suggestedConnection: 'Suggested Connection',
  sharedClass: 'Shared Class',
  academicRegistry: 'Academic Registry',
  collaborationFeedback: 'Collaboration Feedback',
  endorsements: 'Endorsements',
  collaborationScore: 'Collaboration score',
  swipeToSave: 'Swipe right to save. Swipe up to continue.',
  mutualConnectTitle: 'You both want to connect',
  mutualConnectSubtitle: (name: string) => `You and ${name} both want to connect.`,
  startChat: 'Start Chat',
  keepExploring: 'Keep Exploring',
  findConnections: 'Find Connections',
  editProfile: 'Edit Profile',
  myClasses: 'My Classes',
  recentConnections: 'Recent Connections',
  metVia: (code: string) => `Connected through ${code}`,
  shared: (name: string) => `Shared: ${name}`,
  reviews: 'Reviews',
  addReview: 'Add review',
  emptyExplore: 'Nothing new here right now. Check back soon.',
  emptySaved: 'Save classes, professors, or TAs from Explore to build your registry.',
  emptyChat: 'When you connect with classmates, conversations appear here.',
} as const;
